### ISSUE TITLE
dev-status breaks its own EXIT 0 ALWAYS contract: a nan qty escapes the job, and a bare except renders a code defect as a broker outage

### ISSUE THREAD

**Issue by benjaminematton** [benjaminematton/fund#140]
`scripts/dev_status.py` promises, in its own module docstring (`:14`):

> **EXIT 0 ALWAYS.** A check that cannot run renders as a finding. A non-zero exit […]

Two defects in `_positions_and_coverage()` break that promise in opposite directions: one lets a real exception escape the job entirely, and the other converts a deterministic code defect into a message that reads like a transient outage. Both were found while fixing #119 and are recorded here because **#119's thread is where they currently live and #119 is about to close** — closing it would retire the only record of either.

Neither is fixed by #121. Line numbers below are against `origin/master` = `d3a4430`; on the #121 branch they shift by +1 after the import.

---

## 1. A `nan`/`inf` position qty escapes the job and exits non-zero

`state/protection.py:qty_of` guards only the `float()` conversion:

```python
try:
    n = float(value)
except (TypeError, ValueError):
    return None
if n != int(n) or n <= 0:      # <-- int(float("nan")) raises HERE, outside the try
    return None
```

`float("nan")` and `float("inf")` both convert fine, so the guard passes them through to `int(n)`, which raises `ValueError: cannot convert float NaN to integer` and `OverflowError` respectively. Neither is caught.

The position loop (`scripts/dev_status.py:269-280`) sits **outside** both `try` blocks in the function — the second one closes at `:267` — and neither `build_snapshot()` nor `main()` wraps the call. So the exception propagates out of the job.

**DEMONSTRATED** (independent reviewer, against a stubbed broker returning `qty="nan"`):

```
=== #121 branch ===
ESCAPED: ValueError cannot convert float NaN to integer
=== master (d3a4430) ===
result: (None, [], None, "broker client unavailable: cannot import name '_CLOSING_SIDE' ...")
```

### This is not a regression in #121 — it is an un-masking, and that distinction matters

The hole predates the protection-record move: `qty_of` is **AST-identical** to the `_qty` it replaced (verified by extracting the pre-move function and diffing bodies, plus 28 adversarial inputs producing zero differences including identical exception types). Before the move, `dev_status` called `_qty` through the same unguarded loop and was equally exposed.

What changed is only that the broken import was failing first and returning an error tuple, so the loop never ran. #121 restores the import and therefore restores the pre-move exposure. **The correct reading is that this hole has been reachable for as long as the checker worked, and was invisible for exactly as long as the checker was broken.**

### Contrast — the trading path fails closed here and the checker does not

`orchestrator/protection.py:_evaluate` has the same hole, but `assert_positions_protected` wraps it and converts the failure into a `protection_unverified` alert. The orchestrator fails closed, per invariant 4. `dev_status` does not: it exits non-zero, which is the one thing its docstring says it must never do.

**REASONED, not demonstrated:** Alpaca returns decimal strings for `qty`, so a real `nan`/`inf` is unlikely in practice. This is a contract violation and a latent crash, not an active incident. Nobody has observed it in production.

---

## 2. A bare `except Exception` around an import renders a code defect as an outage

`scripts/dev_status.py:248-252`:

```python
try:
    from market.source_alpaca import AlpacaSource
    from orchestrator.protection import _CLOSING_SIDE, _covering_qty, _qty
except Exception as exc:
    return None, [], None, f"broker client unavailable: {exc}"
```

An `ImportError` — hard, deterministic, reproducible on any machine, fixable in two lines — is reported as `broker client unavailable`, which reads as a network or credentials problem and invites *waiting* rather than *fixing*. **This is the mechanism by which #119 went unnoticed.** Credit to `fund-6b`, which hit the same break independently from another lane.

### The fix is to classify, not to stop catching

`CLAUDE.md` invariant 4 requires every ambiguity to resolve to a finding, so removing the handler is wrong — an unreachable broker must still render as a row rather than a traceback. What is missing is the distinction between:

- an `ImportError`, which means *this program is broken and no amount of waiting helps*, and
- a connection or credentials failure, which means *the environment is not ready*.

Both should alert; they should not alert with the same words. Note the credentials case is already distinguished further down (`:254-261`), which is the precedent for the shape of the fix.

**Both defects are in the same failure-handling seam**, which is why they are filed together: one seam either fails open (defect 1) or misdescribes (defect 2), and a repair to either should account for the other.

---

## Also noticed, unrelated and trivial — a stale pointer

`market/source_alpaca.py:194` carries a prose comment reading:

> `_CLOSING_SIDE at protection.py:41-44`

Wrong on both counts since the protection-record move: the name is now `CLOSING_SIDE` and it lives at `state/protection.py:30`. Nothing executes it, but it is a pointer a reader will follow to the wrong place. Recorded here only so it is not lost; it is not part of the seam above and could be split out if that is cleaner.

---

## Provenance

Defect 1 was found by the independent reviewer of #121 while fuzzing `qty_of` against its pre-move twin. Defect 2 was found by `fund-6b`. The stale pointer was found by #121's implementer. All three were deliberately kept out of #121 to preserve a surgical diff on a live blind spot.
